---
- name: Hello World Hashicorp!
  hosts: all

  tasks:

  - name: Hello World!
    shell: echo "Hi! Tower is working!"

  - name: Hashicorp lookup
    debug:
     msg: "{{ lookup('hashi_vault', 'secret=secret/data/hello token=s.2IaLRxRGXfrQjlKrZRc0mw00 url=http://ec2-3-1-221-244.ap-southeast-1.compute.amazonaws.com:8200')}}"